---
abstract: 'Bibliographic Wikidata object defined by MARC record.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::NoWarnings: 0
  Unicode::UTF8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MARC-Convert-Wikidata-Object
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Business::ISBN: 0
  Error::Pure: 0
  List::MoreUtils: 0
  List::Util: 0
  Mo: 0
  Mo::utils: 0.26
  Mo::utils::Date: 0.04
  Readonly: 0
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/MARC-Convert-Wikidata-Object/issues
  homepage: https://github.com/michal-josef-spacek/MARC-Convert-Wikidata-Object
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/MARC-Convert-Wikidata-Object
version: '0.09'
